### ISSUE TITLE
Improve error message if missing top-level environment URL configuration

### ISSUE THREAD

**Issue by lalver1** [cal-itp/littlepay#74]
If there are missing URLs in the top-level environment configuration (`.config/config.yaml`), such as

```yaml
envs:
  prod:
    url: ''
    version: v1
  qa:
    url: ''
    version: v1
```

the CLI should output a better error message to let the user know that the configuration is incomplete.
Currently the user sees a Traceback ending in

```
raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/v1/oauth/token': No scheme supplied. Perhaps you meant https:///api/v1/oauth/token?
```

when attempting to switch to an incompletely configured environment, but a message mentioning a missing configuration would be more helpful.
